[global/wm]
include-file = ~/.config/polybar/colors.ini

[bar/mybar]
modules-left = left bspwm right big-space
modules-center = big-space date big-space
modules-right = light-left pulseaudio light-right small-space light-left xkeyboard light-right tray

width = 100%
height = 22
offset-x = 0%
offset-y = 0%
radius = 0.0
fixed-center = true
wm-restack = bspwm
override-redirect = false

background = ${colors.background}

; fonts
font-0 = Iosevka Nerd Font:size=18;2
font-1 = Noto Sans CJK JP:style=Bold:size=11;2
font-2 = Iosevka Nerd Font:size=14;3
font-3 = Iosevka Nerd Font:size=13;5
font-4 = Iosevka Nerd Font:size=13;4
font-5 = Iosevka Nerd Font:size=13;2
font-6 = DaddyTimeMono Nerd Font:style=Bold:size=12;4
font-7 = DaddyTimeMono Nerd Font:size=12;2

line-size = 2

border-size = 7
border-color = ${colors.background}

[module/bspwm]
type = internal/bspwm

ws-icon-0=1;一
ws-icon-1=2;二
ws-icon-2=3;三
ws-icon-3=4;四
ws-icon-4=5;五
ws-icon-5=6;六
ws-icon-6=7;七
ws-icon-7=8;八

format = <label-state>

label-focused = %icon%
label-focused-foreground = ${colors.desktop-label}
label-focused-background = ${colors.round-background}
label-focused-underline = ${colors.desktop-underline}
label-focused-padding = 1

label-occupied = %icon%
label-occupied-foreground = ${colors.desktop-label}
label-occupied-background = ${colors.round-background}
label-occupied-padding = 1

label-urgent = %icon%
label-urgent-foreground = ${colors.red}
label-urgent-background = ${colors.round-background}
label-urgent-padding = 1
 
label-empty = %icon%
label-empty-foreground = ${colors.desktop-empty}
label-empty-background = ${colors.round-background}
label-empty-padding = 1

[module/left]
type = custom/text
content = %{T3}%{T-}
content-background = ${colors.background}
content-foreground = ${colors.round-background}

[module/right]
type = custom/text
content = %{T3}%{T-}
content-background = ${colors.background}
content-foreground = ${colors.round-background}

[module/light-left]
type = custom/text
content = %{T3}%{T-}
content-background = ${colors.background}
content-foreground = ${colors.desktop-underline}

[module/light-right]
type = custom/text
content = %{T3}%{T-}
content-background = ${colors.background}
content-foreground = ${colors.desktop-underline}

[module/big-space]
type = custom/text
content = "    "
content-background = ${colors.background}
content-foreground = ${colors.background}

[module/small-space]
type = custom/text
content = " "
content-background = ${colors.background}
content-foreground = ${colors.background}

[module/date]
type = internal/date
time-alt = "󰃭  %d %b, %H:%M"
time = "%H:%M"
label = %{T7}%time%%{T-}
label-foreground = ${colors.desktop-underline}

[module/pulseaudio]
type = internal/pulseaudio

format-volume = %{B#D0CFCF}%{F#0f0f17}%{T5}<ramp-volume> <label-volume>%{T-}%{F-}%{B-}

format-muted = %{B#D0CFCF}%{F#0f0f17}%{T4}<label-muted>%{T-}%{F-}%{B-}

label-volume = "%percentage% "
label-muted = "󰝟 " 

ramp-volume-0 = "  "
ramp-volume-1 = "  "
ramp-volume-2 = "  "
ramp-volume-3 = "  "
ramp-volume-4 = "  "
ramp-volume-5 = "  "
ramp-volume-6 = "  "
ramp-volume-7 = "  "
ramp-volume-8 = "  "
ramp-volume-9 = "  "

click-right = pavucontrol

[module/tray]
type = internal/tray
format-margin = 15px
tray-spacing = 15px
tray-size = 85%

[module/sep]
type = custom/text
format = " |"
content-background = ${colors.background}
content-foreground = ${colors.desktop-underline}

[module/xkeyboard]
type = internal/xkeyboard

blacklist-0 = num lock
blacklist-1 = scroll lock
format = %{B#D0CFCF}%{F#0f0f17}%{T6}<label-layout>%{T-}%{F-}%{B-}
label-layout-padding = 1

layout-icon-0 = ru
layout-icon-1 = us
