#!/bin/bash

# Terminate already running bar instances
killall -q polybar

# Ждём завершения
while pgrep -x polybar >/dev/null; do sleep 1; done

# Launch Polybar, using default config location ~/.config/polybar/config
polybar -c $HOME/.config/polybar/config.ini -r mybar 2>&1 | tee -a /tmp/polybar.log & disown
