#! /bin/bash

# Prerequisites
pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr
xrandr --output DP-4 --mode 2560x1600 --rate 165 --primary

# Layouts
$HOME/.config/bspwm/scripts/change_language &

# Polybar
$HOME/.config/polybar/launch_polybar &

# BSPWM settings
bspc monitor primary -d 1 2 3 4 5 6 7 8
bspc config top_padding 56
bspc config border_width 0
bspc config window_gap 0
bspc config focus_follows_pointer true

# Picom
picom --config ~/.config/picom/picom.conf &

# Wallpaper
$HOME/.config/bspwm/scripts/wallpaper

# Background scripts
pgrep -x battery_alert > /dev/null || $HOME/.config/bspwm/scripts/battery_alert &
